# Reflectivity used in the FOXSISIM

How to read HDF5 files?

### Generalities on HDF5 files:

**HDF** stands for Hierarchical Data Format. <br/>
A HDF5 file is a **container** for **datasets** and **groups**. <br/>
**Groups work like containers, datasets work like Numpy arrays**.

In [1]:
import numpy as np
import h5py
''' Read the file '''
f = h5py.File('reflectivity_data_works.hdf5','r') ## Object Dictionary-like.

In [2]:
'''Chechk the keys:'''
list(f.keys())

['angle', 'energy', 'reflectivity']

In [46]:
f['reflectivity/ir']

<HDF5 dataset "ir": shape (30, 501), type "<f8">

In [50]:
f['reflectivity/ir'][()][:,2]

array([0.986524, 0.979129, 0.982429, 0.984373, 0.985721, 0.986736,
       0.987518, 0.988108, 0.988491, 0.988226, 0.973758, 0.965073,
       0.964872, 0.966992, 0.968545, 0.969829, 0.970942, 0.97193 ,
       0.972822, 0.973635, 0.974382, 0.975071, 0.975711, 0.976306,
       0.976862, 0.977382, 0.977869, 0.978328, 0.978748, 0.      ])

In [49]:
f['angle'][()]

array([ 0.  ,  0.02,  0.04,  0.06,  0.08,  0.1 ,  0.12,  0.14,  0.16,
        0.18,  0.2 ,  0.22,  0.24,  0.26,  0.28,  0.3 ,  0.32,  0.34,
        0.36,  0.38,  0.4 ,  0.42,  0.44,  0.46,  0.48,  0.5 ,  0.52,
        0.54,  0.56,  0.58,  0.6 ,  0.62,  0.64,  0.66,  0.68,  0.7 ,
        0.72,  0.74,  0.76,  0.78,  0.8 ,  0.82,  0.84,  0.86,  0.88,
        0.9 ,  0.92,  0.94,  0.96,  0.98,  1.  ,  1.02,  1.04,  1.06,
        1.08,  1.1 ,  1.12,  1.14,  1.16,  1.18,  1.2 ,  1.22,  1.24,
        1.26,  1.28,  1.3 ,  1.32,  1.34,  1.36,  1.38,  1.4 ,  1.42,
        1.44,  1.46,  1.48,  1.5 ,  1.52,  1.54,  1.56,  1.58,  1.6 ,
        1.62,  1.64,  1.66,  1.68,  1.7 ,  1.72,  1.74,  1.76,  1.78,
        1.8 ,  1.82,  1.84,  1.86,  1.88,  1.9 ,  1.92,  1.94,  1.96,
        1.98,  2.  ,  2.02,  2.04,  2.06,  2.08,  2.1 ,  2.12,  2.14,
        2.16,  2.18,  2.2 ,  2.22,  2.24,  2.26,  2.28,  2.3 ,  2.32,
        2.34,  2.36,  2.38,  2.4 ,  2.42,  2.44,  2.46,  2.48,  2.5 ,
        2.52,  2.54,

In [42]:
f['reflectivity/ir'][()].shape

(30, 501)

In [8]:
D_angle[0:501:50]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
D_energy = f['energy']
D_energy[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [22]:
D_ref = f['reflectivity']#f['reflectivity']
type(D_ref)

h5py._hl.group.Group

### Creating a HDF5 file:

In [1]:
import h5py
import numpy as np
f = h5py.File("mytestfile.hdf5", "w") ## This is a group.

In [2]:
dset = f.create_dataset("mydataset",(100,), dtype='i')

In [3]:
dset.name

'/mydataset'

In [4]:
f.name

'/'

In [5]:
f = h5py.File("mytestfile.hdf5","a")
grp = f.create_group("subgroup")

In [6]:
dset2 = grp.create_dataset("another_dataset",(50,),dtype='f')
dset2.name

'/subgroup/another_dataset'

In [8]:
f = h5py.File('reflectivity_data.hdf5','r')

In [10]:
list(f.keys())

['angle', 'energy', 'reflectivity']

In [1]:
import h5py
filename = 'reflectivity_data.hdf5'
f = h5py.File(filename, 'r')

# List all groups
print("Keys: %s" % f.keys())
a_group_key = list(f.keys())[0]

# Get the data
data = list(f[a_group_key])

Keys: KeysView(<HDF5 file "reflectivity_data.hdf5" (mode r)>)


In [24]:
list(f.keys())

['angle', 'energy', 'reflectivity']

In [8]:
a_group_key

'angle'

list

In [32]:
material='Ir'
h = h5py.File("reflectivity_data.hdf5", 'r')

In [33]:
data = h['reflectivity/' + material.lower()][:]

In [37]:
h['reflectivity/ir'].shape

(30, 501)

### Reading every txt file in the "Iridium" folder

In [27]:
rm 'reflectivity_data.hdf5'

In [28]:
import glob
import numpy as np
import h5py
auxR, auxA = [], []

for file in glob.glob('Iridium/*.txt'):
    auxR.append(np.loadtxt(file)[:,1])
    auxA.append(np.loadtxt(file)[:,0])

f = h5py.File('reflectivity_data.hdf5', 'a')
datar = f.create_dataset('reflectivity/ir', (30, 500), dtype='f',data=np.array(auxR))
dataa = f.create_dataset('angle', (500,), dtype='f',data=auxA[0]*0.18/np.pi)
dataa = f.create_dataset('energy', (30,), dtype='f',data=np.arange(1,31,1))

In [29]:
list(f.keys())

['angle', 'energy', 'reflectivity']

In [ ]:
## Check these lines:

h = h5py.File(os.path.join(path, "reflectivity_data.hdf5"), 'r')
         data = np.loadtxt(files[0], skiprows=2)		         self.data = h['reflectivity/' + material.lower()][:]
         energy = int(re.findall(r"\D(\d{2})\D", files[0])[0])		         self.energy_ax = h['energy'][:]
         energy_ax = []		         self.angle_ax = h['angle'][:]