# Debugging Source Randomness of the FOXSISIM at passing rays

### @Milo Dec, 2017

### Task 2:

Check the angular distribution of the rays after they hit the optics module.<br>

To check the previous test were the randomness of the source was tested, <a href="https://github.com/pymilo/Milo_RayTracing/blob/master/Notebooks/Source_Debuging_00.ipynb">check this notebook.</a>

Let's create first an on-axis source with the default parameters:

In [52]:
import numpy as np
from foxsisim.source import Source
from foxsisim.module import Module
#source = Source(type='point')
Sdist = -1000           ## cm
offaxisAngle = 30.0   ## arcmin
source = Source(type='point',center=[0, -Sdist * np.sin(np.deg2rad(offaxisAngle / 60.0)), Sdist ])
module = Module(core_radius=3.36)
n = 1000
rays = source.generateRays(module.targetFront,n)

r0 =  5.340631866960363
r1 =  3.36


### Figuring out how to extract information on where the rays hit the module

In [53]:
rays[1].tag

'Source'

In [54]:
module.passRays(rays)

In [55]:
rays[0].bounces, rays[0].tag, rays[0].hist, rays[0].des,rays[0].pos

(1,
 'Source-Hy',
 [array([    0.       ,     8.7265355, -1000.       ]),
  array([ -3.5939971 ,  -0.49758545,  41.95306046])],
 array([ 0.,  0.,  0.]),
 array([ -3.5939971 ,  -0.49758545,  41.95306046]))

In [62]:
brays = [ray.bounces for ray in rays]
prays = [ray.pos for ray in rays]

In [61]:
drays

[array([ -3.5939971 ,  -0.49758545,  41.95306046]),
 array([ -1.55122216,   3.16227535,  49.34282522]),
 array([  4.45197946,   1.142912  ,  58.52737515]),
 array([  1.49950152,   3.35946304,  51.3034003 ]),
 array([ -4.1597821 ,  -0.75844561,  26.50310504]),
 array([  3.31291017,   1.7692619 ,  46.22584274]),
 array([  1.55173632,  -3.50706976,  22.37676577]),
 array([  3.67700973,   3.15296196,  45.85399486]),
 array([ -4.64884158,   0.31081172,  29.96219933]),
 array([-5.02537851,  0.38249418,  6.82645898]),
 array([  3.31524519,  -1.5950063 ,  38.40988313]),
 array([  4.85447403,  -1.94427404,  17.73612827]),
 array([  3.55918441,  -1.1489473 ,  34.13547214]),
 array([  1.07608171,  -3.88931028,  22.88195289]),
 array([  3.5277664 ,   0.68743904,  44.33673277]),
 array([  4.81921876,  -1.00707732,  26.18297115]),
 array([  1.62971929,   3.06345351,  52.97632633]),
 array([  2.62548426,  -2.8268878 ,  17.46952246]),
 array([ -4.01258326,  -1.89265317,  28.63520481]),
 array([ -0.819