# Time performance foxsisim before reflecivity speed up

Using the **cProfile** python module (suggested by Albert Shi) we were able to test the performance of the program and find out the reason the inclusion of the energy response was taking so much time of the simulation. After some close look of the problem we found the the function responsable for 98% of the procesing time was the *griddata* function in *reflectivity.py*. Wroking with Steven Christe, we changed the function to **inter2d** that not only will work faster but also will give the right reflectivity of the foxsi optics (we found a bug in the old version). <br /> 

Today, July 11, 2017, Steven merged the foxsisim repository with the new version of the reflectivity. The idea is to run this notebook as well as *Time-testing-reflectivity-after-speed-up* to check the inprovement in time.

## Including Energy response for 1000 rays

In [2]:
import cProfile
from foxsisim.module import Module
from foxsisim.detector import Detector
from foxsisim.source import Source
from foxsisim.plotting import plot,scatterHist
import matplotlib.pyplot as plt
import numpy as np

max_energy = 30.0
nrays = 1000

def spectrum(z):
        if (type(z) is not type([1])) and (type(z) is not type(np.array(1))):
            x = np.array([z])
        else:
            x = np.array(z)
        return np.piecewise(x, [x < 0, ((x < max_energy) & (x > 0)), (x >= max_energy)], [0, 1./max_energy, 0])

source_distance = -1e4 ##cm
source = Source(type='point', center=[0, 0, source_distance])
source.loadSpectrum(spectrum)
energies = np.arange(-10, 60, 0.1)

module = Module(radii=[5.151,4.9],focal=200.0)
detector = Detector(width=8,
                    height=8,
                    normal = [0,0,1],
                    center = [0,0,230],
                    reso = [1024,1024])

In [3]:
cProfile.run('rays = source.generateRays(module.targetFront, nrays)')

         55060236 function calls (55060232 primitive calls) in 69.692 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  2007453   15.820    0.000   62.082    0.000 <ipython-input-2-9ae8287834ed>:12(spectrum)
        1    0.000    0.000   69.692   69.692 <string>:1(<module>)
        3    0.000    0.000    0.000    0.000 <string>:12(__new__)
        1    0.000    0.000    0.000    0.000 <string>:2(<module>)
     8421    0.002    0.000    0.002    0.000 <string>:2(_parse_args)
        1    0.000    0.000    0.000    0.000 <string>:5(_parse_args_rvs)
        1    0.000    0.000    0.001    0.001 _distn_infrastructure.py:1484(__init__)
     8421    0.026    0.000   69.637    0.008 _distn_infrastructure.py:1565(_ppf_to_solve)
     1000    0.011    0.000   69.665    0.070 _distn_infrastructure.py:1568(_ppf_single)
     8421    0.327    0.000   69.610    0.008 _distn_infrastructure.py:1706(cdf)
        3    0.000    0.000    0.000 

In [4]:
cProfile.run('module.passRays(rays, robust=True)')

[ 0.  0.  0.]
0 ray bounce number 1
[-5.22344354 -1.06378599  1.60356627]
x =  None
0 ray killed by reflect
[array([     0.,      0., -10000.]), array([-5.22344354, -1.06378599,  1.60356627])]
[ 0.  0.  0.]
[ 0.  0.  0.]
1 ray bounce number 1
[-4.54056614 -2.75174951  5.02851684]
x =  None
1 ray killed by reflect
[array([     0.,      0., -10000.]), array([-4.54056614, -2.75174951,  5.02851684])]
[ 0.  0.  0.]
[ 0.  0.  0.]
2 ray bounce number 1
[-5.15576604  1.23976662  6.0828502 ]
x =  [ 0.01267457 -0.00304775  0.99991503]
2 ray bounce number 2
[ -4.5349976    1.0904953   55.05616489]
x =  None
2 ray killed by reflect
[array([     0.,      0., -10000.]), array([-5.15576604,  1.23976662,  6.0828502 ]), array([ -4.5349976 ,   1.0904953 ,  55.05616489])]
[ 0.  0.  0.]
[ 0.  0.  0.]
3 ray bounce number 1
[  4.17888595   3.08058667  23.662364  ]
x =  None
3 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.17888595,   3.08058667,  23.662364  ])]
[ 0.  0.  0.]
[ 0.  0. 

x =  [-0.00524788 -0.01222724  0.99991147]
34 ray bounce number 2
[  1.98470602   4.62424396  36.14458856]
x =  [-0.01002471 -0.02335696  0.99967693]
34 ray bounce number 3
[  1.98470602   4.62424396  36.14458856]
x =  None
34 ray killed by reflect
[array([     0.,      0., -10000.]), array([  2.04518651,   4.7651598 ,  24.62086581]), array([  1.98470602,   4.62424396,  36.14458856]), array([  1.98470602,   4.62424396,  36.14458856])]
[ 0.  0.  0.]
[ 0.  0.  0.]
35 ray bounce number 1
[ 4.57367456  2.72291829  2.85842442]
x =  [-0.01116234 -0.00664545  0.99991562]
35 ray bounce number 2
[  3.95776176   2.35623715  58.03152808]
x =  [-0.02248135 -0.01338418  0.99965767]
35 ray bounce number 3
[  3.95776176   2.35623715  58.03152808]
x =  None
35 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 4.57367456,  2.72291829,  2.85842442]), array([  3.95776176,   2.35623715,  58.03152808]), array([  3.95776176,   2.35623715,  58.03152808])]
[ 0.  0.  0.]
[ 0.  0.  0.]
36 ray b

x =  None
65 ray killed by reflect
[array([     0.,      0., -10000.]), array([  3.73929408,   3.51189582,  31.09291452])]
[ 0.  0.  0.]
[ 0.  0.  0.]
66 ray bounce number 1
[ 1.62986887  5.03199071  8.21712929]
x =  None
66 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 1.62986887,  5.03199071,  8.21712929])]
[ 0.  0.  0.]
[ 0.  0.  0.]
67 ray bounce number 1
[  4.40839235   2.88344595  11.67348282]
x =  None
67 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.40839235,   2.88344595,  11.67348282])]
[ 0.  0.  0.]
[ 0.  0.  0.]
68 ray bounce number 1
[ 4.28066397 -3.12839098  6.20394078]
x =  None
68 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 4.28066397, -3.12839098,  6.20394078])]
[ 0.  0.  0.]
[ 0.  0.  0.]
69 ray bounce number 1
[ -2.73553036   4.42096599  22.53198668]
x =  None
69 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -2.73553036,   4.42096599,  22.53198668])]
[ 0.  0.  0.]
[ 0.  0.  0.]
7

x =  None
102 ray killed by reflect
[array([     0.,      0., -10000.]), array([-4.60840831,  2.67336986,  2.0811048 ])]
[ 0.  0.  0.]
[ 0.  0.  0.]
103 ray bounce number 1
[-4.80142023  2.2220099   8.01264199]
x =  [ 0.01185515 -0.00548635  0.99991467]
103 ray bounce number 2
[ -4.26526408   1.97388659  53.23437123]
x =  [ 0.02358382 -0.01091416  0.99966229]
[array([     0.,      0., -10000.]), array([-4.80142023,  2.2220099 ,  8.01264199]), array([ -4.26526408,   1.97388659,  53.23437123])]
[ 0.  0.  0.]
[ 0.  0.  0.]
104 ray bounce number 1
[  1.20321655  -5.08311575  18.64573922]
x =  None
104 ray killed by reflect
[array([     0.,      0., -10000.]), array([  1.20321655,  -5.08311575,  18.64573922])]
[ 0.  0.  0.]
[ 0.  0.  0.]
105 ray bounce number 1
[ -3.89777798   3.53505892  12.56115625]
x =  None
105 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -3.89777798,   3.53505892,  12.56115625])]
[ 0.  0.  0.]
[ 0.  0.  0.]
106 ray bounce number 1
[  1.26473228   

x =  None
135 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.96521273,   1.41517976,  28.14123197])]
[ 0.  0.  0.]
[ 0.  0.  0.]
136 ray bounce number 1
[ -4.62943511  -2.42164114  18.49164167]
x =  None
136 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.62943511,  -2.42164114,  18.49164167])]
[ 0.  0.  0.]
[ 0.  0.  0.]
137 ray bounce number 1
[ -4.29042715   3.01233118  15.68865865]
x =  None
137 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.29042715,   3.01233118,  15.68865865])]
[ 0.  0.  0.]
[ 0.  0.  0.]
138 ray bounce number 1
[  4.96777524  -1.5691008   20.83107445]
x =  None
138 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.96777524,  -1.5691008 ,  20.83107445])]
[ 0.  0.  0.]
[ 0.  0.  0.]
139 ray bounce number 1
[ -5.07510358  -0.87544103  30.04889256]
x =  None
139 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -5.07510358,  -0.87544103,  30.04889256])]
[ 0.  0.

x =  None
165 ray killed by reflect
[array([     0.,      0., -10000.]), array([-3.01013718,  4.35506244,  7.46180739])]
[ 0.  0.  0.]
[ 0.  0.  0.]
166 ray bounce number 1
[ -2.85860504   4.25106327  31.45919201]
x =  None
166 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -2.85860504,   4.25106327,  31.45919201])]
[ 0.  0.  0.]
[ 0.  0.  0.]
167 ray bounce number 1
[ 4.71595098 -2.37211816  9.87979171]
x =  None
167 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 4.71595098, -2.37211816,  9.87979171])]
[ 0.  0.  0.]
[ 0.  0.  0.]
168 ray bounce number 1
[  0.85535409   5.13428956  21.55950536]
x =  None
168 ray killed by reflect
[array([     0.,      0., -10000.]), array([  0.85535409,   5.13428956,  21.55950536])]
[ 0.  0.  0.]
[ 0.  0.  0.]
169 ray bounce number 1
[-1.35325509  5.10409881  9.63874379]
x =  None
169 ray killed by reflect
[array([     0.,      0., -10000.]), array([-1.35325509,  5.10409881,  9.63874379])]
[ 0.  0.  0.]
[ 0.  0. 

x =  None
200 ray killed by reflect
[array([     0.,      0., -10000.]), array([  5.01062303,   1.10685209,  31.01357029])]
[ 0.  0.  0.]
[ 0.  0.  0.]
201 ray bounce number 1
[  0.19254905   5.16213291  27.70967578]
x =  None
201 ray killed by reflect
[array([     0.,      0., -10000.]), array([  0.19254905,   5.16213291,  27.70967578])]
[ 0.  0.  0.]
[ 0.  0.  0.]
202 ray bounce number 1
[ -1.51996776  -5.04041395  12.15764729]
x =  None
202 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -1.51996776,  -5.04041395,  12.15764729])]
[ 0.  0.  0.]
[ 0.  0.  0.]
203 ray bounce number 1
[ -2.07287037   4.72487068  28.66713091]
x =  None
203 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -2.07287037,   4.72487068,  28.66713091])]
[ 0.  0.  0.]
[ 0.  0.  0.]
204 ray bounce number 1
[  0.94288946  -5.14239751  17.92954355]
x =  None
204 ray killed by reflect
[array([     0.,      0., -10000.]), array([  0.94288946,  -5.14239751,  17.92954355])]
[ 0.  0.

x =  None
234 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -3.72708914,   3.60643473,  24.49979603])]
[ 0.  0.  0.]
[ 0.  0.  0.]
235 ray bounce number 1
[ 4.5140509   2.78424673  5.93597212]
x =  None
235 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 4.5140509 ,  2.78424673,  5.93597212])]
[ 0.  0.  0.]
[ 0.  0.  0.]
236 ray bounce number 1
[ 2.50370034 -4.71649274  0.1286158 ]
x =  None
236 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 2.50370034, -4.71649274,  0.1286158 ])]
[ 0.  0.  0.]
[ 0.  0.  0.]
237 ray bounce number 1
[ -0.85251634   5.11767653  24.20074927]
x =  [ 0.00218536 -0.01311875  0.99991156]
237 ray bounce number 2
[ -0.85251634   5.11767653  24.20074927]
x =  None
237 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -0.85251634,   5.11767653,  24.20074927]), array([ -0.85251634,   5.11767653,  24.20074927])]
[ 0.  0.  0.]
[ 0.  0.  0.]
238 ray bounce number 1
[ 5.07026283 -1.51241055  

x =  None
268 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -1.04149239,   5.01959358,  31.26802776])]
[ 0.  0.  0.]
[ 0.  0.  0.]
269 ray bounce number 1
[ -3.1759276    4.19749502  12.31739466]
x =  None
269 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -3.1759276 ,   4.19749502,  12.31739466])]
[ 0.  0.  0.]
[ 0.  0.  0.]
270 ray bounce number 1
[  2.57253572   4.45524755  30.3300201 ]
x =  None
270 ray killed by reflect
[array([     0.,      0., -10000.]), array([  2.57253572,   4.45524755,  30.3300201 ])]
[ 0.  0.  0.]
[ 0.  0.  0.]
271 ray bounce number 1
[-5.11875825 -1.42994089  4.16072133]
x =  None
271 ray killed by reflect
[array([     0.,      0., -10000.]), array([-5.11875825, -1.42994089,  4.16072133])]
[ 0.  0.  0.]
[ 0.  0.  0.]
272 ray bounce number 1
[ -3.48335305  -3.86331562  22.06621093]
x =  None
272 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -3.48335305,  -3.86331562,  22.06621093])]
[ 0.  0.  0.]


x =  None
301 ray killed by reflect
[array([     0.,      0., -10000.]), array([-3.49143752, -4.00448674,  4.46783079])]
[ 0.  0.  0.]
[ 0.  0.  0.]
302 ray bounce number 1
[ -4.4277284   -2.751555    20.30383624]
x =  [ 0.01124656  0.00698903  0.99991233]
302 ray bounce number 2
[ -4.19666713  -2.60796493  40.84709464]
x =  [ 0.02171403  0.01349391  0.99967315]
302 ray bounce number 3
[ -4.19666713  -2.60796493  40.84709464]
x =  None
302 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.4277284 ,  -2.751555  ,  20.30383624]), array([ -4.19666713,  -2.60796493,  40.84709464]), array([ -4.19666713,  -2.60796493,  40.84709464])]
[ 0.  0.  0.]
[ 0.  0.  0.]
303 ray bounce number 1
[  2.06436766  -4.79152643  19.63274341]
x =  None
303 ray killed by reflect
[array([     0.,      0., -10000.]), array([  2.06436766,  -4.79152643,  19.63274341])]
[ 0.  0.  0.]
[ 0.  0.  0.]
304 ray bounce number 1
[  2.24571703  -4.66006238  26.58276076]
x =  None
304 ray killed by reflec

x =  None
335 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -5.12339899,   0.96579033,  20.21133581])]
[ 0.  0.  0.]
[ 0.  0.  0.]
336 ray bounce number 1
[ -1.5412944    5.00147594  17.06918741]
x =  [ 0.00388553 -0.01260848  0.99991296]
336 ray bounce number 2
[ -1.43569108   4.65879484  44.24545011]
x =  [ 0.00756166 -0.02453746  0.99967031]
336 ray bounce number 3
[ -1.43569108   4.65879484  44.24545011]
x =  None
336 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -1.5412944 ,   5.00147594,  17.06918741]), array([ -1.43569108,   4.65879484,  44.24545011]), array([ -1.43569108,   4.65879484,  44.24545011])]
[ 0.  0.  0.]
[ 0.  0.  0.]
337 ray bounce number 1
[ -1.22611136   5.08054406  18.20119806]
x =  None
337 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -1.22611136,   5.08054406,  18.20119806])]
[ 0.  0.  0.]
[ 0.  0.  0.]
338 ray bounce number 1
[ -2.56873679   4.56278214  16.66146202]
x =  None
338 ray killed by ref

x =  [-0.00219391 -0.01280703  0.99991558]
364 ray bounce number 2
[ 0.89852714  5.24518385  3.06166221]
x =  None
364 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 0.89852714,  5.24518385,  3.06166221]), array([ 0.89852714,  5.24518385,  3.06166221])]
[ 0.  0.  0.]
[ 0.  0.  0.]
365 ray bounce number 1
[ -1.43563041   4.97478883  25.82682644]
x =  None
365 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -1.43563041,   4.97478883,  25.82682644])]
[ 0.  0.  0.]
[ 0.  0.  0.]
366 ray bounce number 1
[-2.29627211 -4.81495274  0.99087749]
x =  [ 0.00558085  0.01170223  0.99991595]
366 ray bounce number 2
[ -1.96850414  -4.12767039  59.71680698]
x =  [ 0.01129009  0.0236737   0.99965599]
[array([     0.,      0., -10000.]), array([-2.29627211, -4.81495274,  0.99087749]), array([ -1.96850414,  -4.12767039,  59.71680698])]
[ 0.  0.  0.]
[ 0.  0.  0.]
367 ray bounce number 1
[-4.48609509 -2.87194073  2.25060201]
x =  None
367 ray killed by reflect
[array

x =  None
395 ray killed by reflect
[array([     0.,      0., -10000.]), array([  3.04224237,  -4.22404473,  21.48060356])]
[ 0.  0.  0.]
[ 0.  0.  0.]
396 ray bounce number 1
[ -4.38499993   2.60948192  32.49904332]
x =  None
396 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.38499993,   2.60948192,  32.49904332])]
[ 0.  0.  0.]
[ 0.  0.  0.]
397 ray bounce number 1
[ -0.96837936   5.13675212  18.06995366]
x =  None
397 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -0.96837936,   5.13675212,  18.06995366])]
[ 0.  0.  0.]
[ 0.  0.  0.]
398 ray bounce number 1
[ -3.85118224   3.58303019  12.85677259]
x =  [ 0.00961467 -0.00894521  0.99991377]
398 ray bounce number 2
[ -3.50826832   3.26399285  48.51940017]
x =  [ 0.0189042  -0.01758793  0.99966659]
398 ray bounce number 3
[ -3.50826832   3.26399285  48.51940017]
x =  None
398 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -3.85118224,   3.58303019,  12.85677259]), array([ -

x =  [-0.02177264 -0.03252456  0.99923376]
429 ray bounce number 2
[  2.85640307   4.26697189  30.83902667]
x =  None
429 ray killed by reflect
[array([     0.,      0., -10000.]), array([  2.85640307,   4.26697189,  30.83902667]), array([  2.85640307,   4.26697189,  30.83902667])]
[ 0.  0.  0.]
[ 0.  0.  0.]
430 ray bounce number 1
[ 0.70047713 -5.28643464  1.28606101]
x =  None
430 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 0.70047713, -5.28643464,  1.28606101])]
[ 0.  0.  0.]
[ 0.  0.  0.]
431 ray bounce number 1
[  0.4152977   -5.21982432  16.63660372]
x =  None
431 ray killed by reflect
[array([     0.,      0., -10000.]), array([  0.4152977 ,  -5.21982432,  16.63660372])]
[ 0.  0.  0.]
[ 0.  0.  0.]
432 ray bounce number 1
[  1.61355552  -4.92873396  24.52369675]
x =  [-0.00413938  0.01264406  0.99991149]
432 ray bounce number 2
[  1.56500079  -4.78041968  36.2526136 ]
x =  [-0.00790911  0.02415901  0.99967684]
432 ray bounce number 3
[  1.56500079  -4.780

x =  None
463 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -3.34975678,  -3.84445812,  32.68606598])]
[ 0.  0.  0.]
[ 0.  0.  0.]
464 ray bounce number 1
[-5.32519112 -0.24274723  1.59476568]
x =  None
464 ray killed by reflect
[array([     0.,      0., -10000.]), array([-5.32519112, -0.24274723,  1.59476568])]
[ 0.  0.  0.]
[ 0.  0.  0.]
465 ray bounce number 1
[  2.26188327   4.63492299  29.00742182]
x =  None
465 ray killed by reflect
[array([     0.,      0., -10000.]), array([  2.26188327,   4.63492299,  29.00742182])]
[ 0.  0.  0.]
[ 0.  0.  0.]
466 ray bounce number 1
[ -1.49520226  -5.0120194   17.58762186]
x =  [ 0.00377387  0.01265028  0.99991286]
466 ray bounce number 2
[ -1.39661963  -4.68156374  43.70774264]
x =  None
466 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -1.49520226,  -5.0120194 ,  17.58762186]), array([ -1.39661963,  -4.68156374,  43.70774264])]
[ 0.  0.  0.]
[ 0.  0.  0.]
467 ray bounce number 1
[  4.50801073   2.42

x =  None
499 ray killed by reflect
[array([     0.,      0., -10000.]), array([  1.10483139,  -5.13665217,  13.81973522])]
[ 0.  0.  0.]
[ 0.  0.  0.]
500 ray bounce number 1
[ -5.00277673  -1.06582171  31.86050825]
x =  None
500 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -5.00277673,  -1.06582171,  31.86050825])]
[ 0.  0.  0.]
[ 0.  0.  0.]
501 ray bounce number 1
[ -4.25469877   3.10541961  11.70501466]
x =  None
501 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.25469877,   3.10541961,  11.70501466])]
[ 0.  0.  0.]
[ 0.  0.  0.]
502 ray bounce number 1
[-4.37381748  3.05502269  0.88822858]
x =  None
502 ray killed by reflect
[array([     0.,      0., -10000.]), array([-4.37381748,  3.05502269,  0.88822858])]
[ 0.  0.  0.]
[ 0.  0.  0.]
503 ray bounce number 1
[ 3.31887588 -4.16682177  2.18654619]
x =  None
503 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 3.31887588, -4.16682177,  2.18654619])]
[ 0.  0.  0.]
[ 0.  

x =  None
529 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -5.2167739 ,   0.75378895,  11.14958419])]
[ 0.  0.  0.]
[ 0.  0.  0.]
530 ray bounce number 1
[-0.36825826 -5.31074874  2.75463293]
x =  None
530 ray killed by reflect
[array([     0.,      0., -10000.]), array([-0.36825826, -5.31074874,  2.75463293])]
[ 0.  0.  0.]
[ 0.  0.  0.]
531 ray bounce number 1
[ -4.37650177   2.66227945  31.46758647]
x =  None
531 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.37650177,   2.66227945,  31.46758647])]
[ 0.  0.  0.]
[ 0.  0.  0.]
532 ray bounce number 1
[-5.23955959  0.79883699  6.50233494]
x =  None
532 ray killed by reflect
[array([     0.,      0., -10000.]), array([-5.23955959,  0.79883699,  6.50233494])]
[ 0.  0.  0.]
[ 0.  0.  0.]
533 ray bounce number 1
[ -0.65733016  -5.21371678  13.68285585]
x =  None
533 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -0.65733016,  -5.21371678,  13.68285585])]
[ 0.  0.  0.]
[ 0.  

x =  None
557 ray killed by reflect
[array([     0.,      0., -10000.]), array([  1.55245770e-02,   5.20124112e+00,   2.21537561e+01])]
[ 0.  0.  0.]
[ 0.  0.  0.]
558 ray bounce number 1
[  4.47653025  -2.49215758  31.42378768]
x =  None
558 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.47653025,  -2.49215758,  31.42378768])]
[ 0.  0.  0.]
[ 0.  0.  0.]
559 ray bounce number 1
[  0.77380096  -5.18594832  15.52394321]
x =  None
559 ray killed by reflect
[array([     0.,      0., -10000.]), array([  0.77380096,  -5.18594832,  15.52394321])]
[ 0.  0.  0.]
[ 0.  0.  0.]
560 ray bounce number 1
[-5.31788362  0.28197579  2.45712465]
x =  None
560 ray killed by reflect
[array([     0.,      0., -10000.]), array([-5.31788362,  0.28197579,  2.45712465])]
[ 0.  0.  0.]
[ 0.  0.  0.]
561 ray bounce number 1
[ -4.46583693   2.76734567  13.87924232]
x =  None
561 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.46583693,   2.76734567,  13.87924232])]
[ 

x =  None
588 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.51697644,  -2.42439144,  31.26942131])]
[ 0.  0.  0.]
[ 0.  0.  0.]
589 ray bounce number 1
[ -5.03850356   1.10924672  28.73118761]
x =  None
589 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -5.03850356,   1.10924672,  28.73118761])]
[ 0.  0.  0.]
[ 0.  0.  0.]
590 ray bounce number 1
[  4.78831109   1.75834992  32.58978718]
x =  None
590 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.78831109,   1.75834992,  32.58978718])]
[ 0.  0.  0.]
[ 0.  0.  0.]
591 ray bounce number 1
[ -4.85473545   2.05329634  11.12614596]
x =  None
591 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.85473545,   2.05329634,  11.12614596])]
[ 0.  0.  0.]
[ 0.  0.  0.]
592 ray bounce number 1
[  2.93403526  -4.35741051  13.97442532]
x =  [-0.00734382  0.01090649  0.99991355]
592 ray bounce number 2
[  2.68853064  -3.99280535  47.40163411]
x =  [-0.01440015  0.021

x =  None
621 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.48546933,   2.76324186,  11.5715954 ])]
[ 0.  0.  0.]
[ 0.  0.  0.]
622 ray bounce number 1
[  4.77969807  -2.09118067  19.6597212 ]
x =  None
622 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.77969807,  -2.09118067,  19.6597212 ])]
[ 0.  0.  0.]
[ 0.  0.  0.]
623 ray bounce number 1
[ -1.19568818   5.10373717  15.75049512]
x =  None
623 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -1.19568818,   5.10373717,  15.75049512])]
[ 0.  0.  0.]
[ 0.  0.  0.]
624 ray bounce number 1
[-4.46115714 -2.86293976  6.39343715]
x =  None
624 ray killed by reflect
[array([     0.,      0., -10000.]), array([-4.46115714, -2.86293976,  6.39343715])]
[ 0.  0.  0.]
[ 0.  0.  0.]
625 ray bounce number 1
[ 2.01925499 -4.92717714  2.53148106]
x =  None
625 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 2.01925499, -4.92717714,  2.53148106])]
[ 0.  0.  0.]
[ 0.  

x =  None
657 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 1.29721902, -5.17926159,  0.22348234])]
[ 0.  0.  0.]
[ 0.  0.  0.]
658 ray bounce number 1
[  4.12292903  -3.07889645  30.27480038]
x =  None
658 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.12292903,  -3.07889645,  30.27480038])]
[ 0.  0.  0.]
[ 0.  0.  0.]
659 ray bounce number 1
[  0.20601144   5.2212626   18.37088119]
x =  None
659 ray killed by reflect
[array([     0.,      0., -10000.]), array([  0.20601144,   5.2212626 ,  18.37088119])]
[ 0.  0.  0.]
[ 0.  0.  0.]
660 ray bounce number 1
[ -2.05001305   4.85972398  10.59856004]
x =  None
660 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -2.05001305,   4.85972398,  10.59856004])]
[ 0.  0.  0.]
[ 0.  0.  0.]
661 ray bounce number 1
[ -4.93049388   1.49814859  29.6770407 ]
x =  None
661 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.93049388,   1.49814859,  29.6770407 ])]
[ 0.  0.  0

x =  None
692 ray killed by reflect
[array([     0.,      0., -10000.]), array([  2.42952783,   4.49375514,  32.20109506])]
[ 0.  0.  0.]
[ 0.  0.  0.]
693 ray bounce number 1
[ -5.16122464   0.27980548  27.22957336]
x =  None
693 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -5.16122464,   0.27980548,  27.22957336])]
[ 0.  0.  0.]
[ 0.  0.  0.]
694 ray bounce number 1
[-5.25081591  0.90403167  2.0206772 ]
x =  None
694 ray killed by reflect
[array([     0.,      0., -10000.]), array([-5.25081591,  0.90403167,  2.0206772 ])]
[ 0.  0.  0.]
[ 0.  0.  0.]
695 ray bounce number 1
[ 5.18185813  1.06869051  7.97058951]
x =  [-0.01279327 -0.00263844  0.99991468]
695 ray bounce number 2
[  4.60222491   0.94914873  53.27440585]
x =  [-0.02545261 -0.00524927  0.99966225]
[array([     0.,      0., -10000.]), array([ 5.18185813,  1.06869051,  7.97058951]), array([  4.60222491,   0.94914873,  53.27440585])]
[ 0.  0.  0.]
[ 0.  0.  0.]
696 ray bounce number 1
[  3.91965657  -3.4

x =  None
725 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.81536832,   1.72379157,  31.88337473])]
[ 0.  0.  0.]
[ 0.  0.  0.]
726 ray bounce number 1
[ -2.23530829   4.75388391  13.967999  ]
x =  [ 0.00559484 -0.01189868  0.99991356]
726 ray bounce number 2
[ -2.04820014   4.3559565   47.40809406]
x =  [ 0.01097083 -0.02333192  0.99966758]
726 ray bounce number 3
[ -2.04820014   4.3559565   47.40809406]
x =  None
726 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -2.23530829,   4.75388391,  13.967999  ]), array([ -2.04820014,   4.3559565 ,  47.40809406]), array([ -2.04820014,   4.3559565 ,  47.40809406])]
[ 0.  0.  0.]
[ 0.  0.  0.]
727 ray bounce number 1
[ -4.72238509  -2.126385    25.63267977]
x =  None
727 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.72238509,  -2.126385  ,  25.63267977])]
[ 0.  0.  0.]
[ 0.  0.  0.]
728 ray bounce number 1
[  4.75533412  -1.85256736  32.46059002]
x =  None
728 ray killed by ref

x =  None
757 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -0.18431199,   5.17462422,  25.8095144 ])]
[ 0.  0.  0.]
[ 0.  0.  0.]
758 ray bounce number 1
[ -4.36545013   2.70862159  30.69946607]
x =  None
758 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.36545013,   2.70862159,  30.69946607])]
[ 0.  0.  0.]
[ 0.  0.  0.]
759 ray bounce number 1
[ -0.65485994   5.13987191  25.26037324]
x =  None
759 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -0.65485994,   5.13987191,  25.26037324])]
[ 0.  0.  0.]
[ 0.  0.  0.]
760 ray bounce number 1
[-2.79905783 -4.53164435  2.28931713]
x =  [ 0.00682258  0.01104568  0.99991572]
760 ray bounce number 2
[ -2.41519639  -3.91017682  58.54799493]
x =  [ 0.01375956  0.02227657  0.99965716]
[array([     0.,      0., -10000.]), array([-2.79905783, -4.53164435,  2.28931713]), array([ -2.41519639,  -3.91017682,  58.54799493])]
[ 0.  0.  0.]
[ 0.  0.  0.]
761 ray bounce number 1
[ -1.18560336

x =  None
792 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 4.29778445,  3.06843638,  9.59156345])]
[ 0.  0.  0.]
[ 0.  0.  0.]
793 ray bounce number 1
[ 5.1898978   1.21509382  1.67158414]
x =  None
793 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 5.1898978 ,  1.21509382,  1.67158414])]
[ 0.  0.  0.]
[ 0.  0.  0.]
794 ray bounce number 1
[-0.67787811  5.23970503  9.17275654]
x =  None
794 ray killed by reflect
[array([     0.,      0., -10000.]), array([-0.67787811,  5.23970503,  9.17275654])]
[ 0.  0.  0.]
[ 0.  0.  0.]
795 ray bounce number 1
[ 1.00574003  5.2411052   0.62806297]
x =  None
795 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 1.00574003,  5.2411052 ,  0.62806297])]
[ 0.  0.  0.]
[ 0.  0.  0.]
796 ray bounce number 1
[  0.48185706  -5.22426078  15.03751468]
x =  None
796 ray killed by reflect
[array([     0.,      0., -10000.]), array([  0.48185706,  -5.22426078,  15.03751468])]
[ 0.  0.  0.]
[ 0.  0.  0.]
7

x =  None
827 ray killed by reflect
[array([     0.,      0., -10000.]), array([-4.33633363,  3.07537042,  3.93038287])]
[ 0.  0.  0.]
[ 0.  0.  0.]
828 ray bounce number 1
[ -0.33143537  -5.09505362  32.33792426]
x =  None
828 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -0.33143537,  -5.09505362,  32.33792426])]
[ 0.  0.  0.]
[ 0.  0.  0.]
829 ray bounce number 1
[ 3.25620519  4.21356622  2.4930721 ]
x =  None
829 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 3.25620519,  4.21356622,  2.4930721 ])]
[ 0.  0.  0.]
[ 0.  0.  0.]
830 ray bounce number 1
[  2.35321902   4.53880648  31.98871647]
x =  None
830 ray killed by reflect
[array([     0.,      0., -10000.]), array([  2.35321902,   4.53880648,  31.98871647])]
[ 0.  0.  0.]
[ 0.  0.  0.]
831 ray bounce number 1
[-4.65962941  2.58090042  2.24908651]
x =  [ 0.01135661 -0.00629026  0.99991573]
831 ray bounce number 2
[ -4.01979711   2.22650669  58.5844075 ]
x =  [ 0.02290585 -0.01268722  0.999

x =  [-0.02799379 -0.02736368  0.99923349]
862 ray bounce number 2
[  3.66540837   3.58290425  31.31145936]
x =  None
862 ray killed by reflect
[array([     0.,      0., -10000.]), array([  3.66540837,   3.58290425,  31.31145936]), array([  3.66540837,   3.58290425,  31.31145936])]
[ 0.  0.  0.]
[ 0.  0.  0.]
863 ray bounce number 1
[ -0.69403516   5.19558976  15.78013424]
x =  None
863 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -0.69403516,   5.19558976,  15.78013424])]
[ 0.  0.  0.]
[ 0.  0.  0.]
864 ray bounce number 1
[ -1.99319171  -4.73524726  30.69143617]
x =  [ 0.01518365  0.03607197  0.99923384]
864 ray bounce number 2
[ -1.80977031  -4.29949105  42.7623705 ]
x =  None
864 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -1.99319171,  -4.73524726,  30.69143617]), array([ -1.80977031,  -4.29949105,  42.7623705 ])]
[ 0.  0.  0.]
[ 0.  0.  0.]
865 ray bounce number 1
[ 5.27610094 -0.74682494  1.92043811]
x =  None
865 ray killed by reflec

x =  None
895 ray killed by reflect
[array([     0.,      0., -10000.]), array([  1.56008895,   5.01685442,  13.86711534])]
[ 0.  0.  0.]
[ 0.  0.  0.]
896 ray bounce number 1
[-1.20808031 -5.15354374  7.59787241]
x =  None
896 ray killed by reflect
[array([     0.,      0., -10000.]), array([-1.20808031, -5.15354374,  7.59787241])]
[ 0.  0.  0.]
[ 0.  0.  0.]
897 ray bounce number 1
[  2.32153172   4.73408147  10.87651988]
x =  None
897 ray killed by reflect
[array([     0.,      0., -10000.]), array([  2.32153172,   4.73408147,  10.87651988])]
[ 0.  0.  0.]
[ 0.  0.  0.]
898 ray bounce number 1
[ -5.23734413   0.26495595  15.41617004]
x =  None
898 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -5.23734413,   0.26495595,  15.41617004])]
[ 0.  0.  0.]
[ 0.  0.  0.]
899 ray bounce number 1
[  3.52639353   3.92450277  10.33162573]
x =  None
899 ray killed by reflect
[array([     0.,      0., -10000.]), array([  3.52639353,   3.92450277,  10.33162573])]
[ 0.  0.  0.]


x =  None
929 ray killed by reflect
[array([     0.,      0., -10000.]), array([  2.67722306,  -4.41317137,  28.32920951])]
[ 0.  0.  0.]
[ 0.  0.  0.]
930 ray bounce number 1
[ -3.6747469   -3.70520891  19.45182122]
x =  None
930 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -3.6747469 ,  -3.70520891,  19.45182122])]
[ 0.  0.  0.]
[ 0.  0.  0.]
931 ray bounce number 1
[ -0.9365492    5.1567373   15.88227381]
x =  None
931 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -0.9365492 ,   5.1567373 ,  15.88227381])]
[ 0.  0.  0.]
[ 0.  0.  0.]
932 ray bounce number 1
[ -3.00233925  -4.15336428  31.35156952]
x =  None
932 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -3.00233925,  -4.15336428,  31.35156952])]
[ 0.  0.  0.]
[ 0.  0.  0.]
933 ray bounce number 1
[  4.85542642  -1.79839131  25.82956437]
x =  None
933 ray killed by reflect
[array([     0.,      0., -10000.]), array([  4.85542642,  -1.79839131,  25.82956437])]
[ 0.  0.

x =  None
966 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -4.46530295,   2.63903378,  24.41136136])]
[ 0.  0.  0.]
[ 0.  0.  0.]
967 ray bounce number 1
[ -3.37298183   3.86540281  31.07973545]
x =  None
967 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -3.37298183,   3.86540281,  31.07973545])]
[ 0.  0.  0.]
[ 0.  0.  0.]
968 ray bounce number 1
[ -3.20428625  -3.99097932  31.70066991]
x =  [ 0.02451154  0.03052943  0.99923328]
968 ray bounce number 2
[ -2.9093954   -3.62368901  43.7221418 ]
x =  None
968 ray killed by reflect
[array([     0.,      0., -10000.]), array([ -3.20428625,  -3.99097932,  31.70066991]), array([ -2.9093954 ,  -3.62368901,  43.7221418 ])]
[ 0.  0.  0.]
[ 0.  0.  0.]
969 ray bounce number 1
[ 0.63098139  5.30300956  0.03469375]
x =  [-0.00153027 -0.01286098  0.99991612]
969 ray bounce number 2
[ 0.63098139  5.30300956  0.03469375]
x =  None
969 ray killed by reflect
[array([     0.,      0., -10000.]), array([ 0.63098

x =  None
998 ray killed by reflect
[array([     0.,      0., -10000.]), array([  0.48760651,  -5.15801735,  25.32403072])]
[ 0.  0.  0.]
[ 0.  0.  0.]
999 ray bounce number 1
[-5.31061899 -0.28777524  3.57156761]
x =  None
999 ray killed by reflect
[array([     0.,      0., -10000.]), array([-5.31061899, -0.28777524,  3.57156761])]
[ 0.  0.  0.]
         3135922 function calls in 353.070 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    34260    0.039    0.000    0.055    0.000 <frozen importlib._bootstrap>:402(parent)
    34260    0.041    0.000    0.059    0.000 <frozen importlib._bootstrap>:989(_handle_fromlist)
        1    0.000    0.000  353.069  353.069 <string>:1(<module>)
        3    0.000    0.000    0.000    0.000 _collections_abc.py:657(get)
     1116    0.002    0.000    0.312    0.000 _methods.py:25(_amax)
     1116    0.003    0.000    0.314    0.000 _methods.py:28(_amin)
    18184    0.011    0.000    0.

In [5]:
detector.catchRays(rays)

In [6]:
len(detector.rays)

53

## No energy response

In [10]:
from foxsisim.module import Module
from foxsisim.detector import Detector
from foxsisim.source import Source
from foxsisim.plotting import scatterHist
from foxsisim.plotting import plot
from foxsisim.util import save_rays
import matplotlib.pyplot as plt
from astropy.io import fits
import numpy as np

In [12]:
module = Module(radii = [5.151,4.9,4.659,4.429,4.21,4.0,3.799], #7Shells
    #module = Module(radii = [5.151,4.9,4.659,4.429,4.21,4.0,3.799,3.59,3.38,3.17], #10Shells
                    seglen=30.0,
                    base=[0,0,0],
                    focal=200,
                    angles=None,
                    conic=False)

detector = Detector(width=10, #27.6 x 27.6 mm values taken from Steven
                    height=10,
                    normal = [0,0,1],
                    center = [0,0,230],
                    reso = [2048,2048]) # Resolution taken from Steven

    #source_distance = -2187.5
source_distance = -1.04e4 #Source distance according to Steve's paper 
offaxis_angle_arcmin = 14.0
source = Source(type='point',
                center=[ source_distance * np.sin(np.deg2rad(offaxis_angle_arcmin/60.0)) , 0.0 , source_distance ],
                color=[1,1,1])
    
photons=100

In [13]:
cProfile.run('rays = source.generateRays(module.targetFront, nrays)')

         1913 function calls in 0.005 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.004    0.004 <string>:1(<module>)
      100    0.000    0.000    0.000    0.000 linalg.py:111(isComplexType)
      100    0.000    0.000    0.001    0.000 linalg.py:2022(norm)
        1    0.000    0.000    0.000    0.000 module.py:242(targetFront)
      100    0.000    0.000    0.000    0.000 numeric.py:463(asarray)
      100    0.000    0.000    0.001    0.000 ray.py:16(__init__)
        1    0.000    0.000    0.000    0.000 segmentp.py:253(targetFront)
        1    0.000    0.000    0.000    0.000 shell.py:75(targetFront)
        1    0.001    0.001    0.004    0.004 source.py:144(generateRays)
        1    0.000    0.000    0.000    0.000 source.py:159(<listcomp>)
        1    0.000    0.000    0.000    0.000 source.py:160(<listcomp>)
        1    0.000    0.000    0.001    0.001 source.py:170(<listcomp

In [14]:
cProfile.run('module.passRays(rays, robust=True)')

         632541 function calls in 0.957 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.957    0.957 <string>:1(<module>)
      100    0.000    0.000    0.002    0.000 circle.py:44(inRange)
     5234    0.002    0.000    0.002    0.000 fromnumeric.py:1549(shape)
      200    0.000    0.000    0.001    0.000 fromnumeric.py:504(transpose)
      200    0.000    0.000    0.000    0.000 fromnumeric.py:55(_wrapfunc)
     2617    0.004    0.000    0.005    0.000 getlimits.py:96(__new__)
      100    0.000    0.000    0.000    0.000 linalg.py:101(get_linalg_error_extobj)
      200    0.000    0.000    0.000    0.000 linalg.py:106(_makearray)
     3365    0.001    0.000    0.002    0.000 linalg.py:111(isComplexType)
      200    0.000    0.000    0.000    0.000 linalg.py:124(_realType)
      100    0.000    0.000    0.001    0.000 linalg.py:139(_commonType)
      100    0.000    0.000    0.000    0.0